drop table if exists member CASCADE;
create table member
(
    userNo bigint generated by default as identity,
    primary key (userNo),
    name varchar(255),
    id varchar(255),
    password varchar(255),
    email varchar(255)
);
